
name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'   # Set Node.js version used by Angular
          cache: 'npm'         # Enables built-in npm caching

      # Install dependencies (uses cache if available)
      - name: Install dependencies
        run: npm ci

      # Run lint (optional)
      - name: Lint Angular app
        run: npm run lint --if-present

      # Run tests (optional)
     

      # Build Angular app
      - name: Build Angular app
        run: npm run build --if-present
